version: '3'
services:
  trojan:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '443:443'
    volumes:
      - certs:/root/.local/share
      - /home/orz/code/docker/volumes/site:/var/www/site

volumes:
  certs: